# Generated by Django 4.1.3 on 2022-11-26 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_qty', models.IntegerField(default=0)),
                ('total_rows', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('INC', 'Incoming'), ('OUT', 'Outgoing')], default='INC', max_length=10, null=True)),
                ('invoiceno', models.CharField(blank=True, max_length=75, null=True)),
                ('OAno', models.CharField(blank=True, max_length=75, null=True)),
                ('remarks', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_description', models.CharField(blank=True, max_length=75, null=True)),
                ('MOQ', models.IntegerField(default=0)),
                ('brand', models.CharField(choices=[('abb', 'ABB'), ('legrand', 'LEGRAND'), ('phoenix mecano', 'PHEONIX MECANO'), ('eaton', 'EATON'), ('Bussmann', 'Bussmann'), ('socomec', 'SOCOMEC'), ('Scame', 'SCAME')], default='Bussmann', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown_assigned', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.godown')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GodownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.godown')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.godownitem')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='godown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.godown'),
        ),
        migrations.AddField(
            model_name='document',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
