# Generated by Django 4.1.3 on 2022-11-28 06:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('INC', 'Incoming')], default='INC', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.item'),
        ),
        migrations.CreateModel(
            name='OutDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
                ('godownitem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.godownitem')),
            ],
        ),
        migrations.CreateModel(
            name='OutDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_qty', models.IntegerField(default=0)),
                ('total_rows', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('OUT', 'Outgoing')], default='OUT', max_length=10, null=True)),
                ('invoiceno', models.CharField(blank=True, max_length=75, null=True)),
                ('OAno', models.CharField(blank=True, max_length=75, null=True)),
                ('remarks', models.CharField(blank=True, max_length=30, null=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.godown')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
