# Generated by Django 4.1.3 on 2022-11-28 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_outdocumentitem_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Document',
            new_name='InDocument',
        ),
        migrations.DeleteModel(
            name='DocumentItem',
        ),
        migrations.AddField(
            model_name='indocumentitem',
            name='indocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indocument'),
        ),
        migrations.AddField(
            model_name='indocumentitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.item'),
        ),
    ]
